create TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(15) NOT NULL UNIQUE,
    birthday TIMESTAMP NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS posts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    photo_url VARCHAR(1000) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    updated_on TIMESTAMP,
    user_id BIGINT REFERENCES users (id) ON delete CASCADE
);

create TABLE IF NOT EXISTS friendship
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON delete CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users (id) ON delete CASCADE,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_friend FOREIGN KEY(friend_id) REFERENCES users(id),
    CONSTRAINT check_user_friend_not_same CHECK (user_id != friend_id),
    CONSTRAINT unique_user_friend_pair UNIQUE (user_id, friend_id)
);

